[package]
name = "importance"
version = "0.1.0"
edition = "2021"

[lib]
name = "importance"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.19.2"
features = ["extension-module", "generate-import-lib"]
