name: Deploy
on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11' 
        - uses: dtolnay/rust-toolchain@stable
          with:
            targets: ${{ matrix.target }}
        - uses: PyO3/maturin-action@v1
          with:
            command: build
            args: --release --out dist
            rust-toolchain: stable
        - uses: actions/upload-artifact@v3
          with:
            name: files
            path: dist
