name: Deploy
on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - uses: dtolnay/rust-toolchain@stable
          with:
            targets: ${{ matrix.target }}
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --verbose --release --target ${{ matrix.target }}
        - uses: actions/upload-artifact@v3
          with:
            path: target/${{ matrix.target }}/release
