name: Deploy
on:
  push:
    tags:
      # Regex for a version number such as 0.2.1
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - uses: dtolnay/rust-toolchain@stable
          with:
            targets: ${{ matrix.target }}
        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --verbose --release --target ${{ matrix.target }}            
